version: "3"

services:
  node-app:
    build: 
      context: .
      target: production
    container_name: express-node-container-prod
    hostname: Host_Prod
    environment:
      - NODE_ENV=production
    command: npm start


      